<a href="https://colab.research.google.com/github/Nihalht/ML_LAB-PR-s/blob/main/PR%20-2-mean-median-mode-bffile-ffile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Nihal H T PR -2 : Handling Missing Vlaues**

In [135]:
#Level 2: User-Defined Functions for missing value Handlings

#step 1 : import lib
import numpy as np
import pandas as pd

In [136]:
#step 2 : Create Sample Dataset with Missing Values
data={
    'Age':[25,30,np.nan,45,50],
    'Salary':[50000,np.nan,60000,65000,np.nan],
    'Experience':[1,3,5,np.nan,10]

}
df= pd.DataFrame(data)
df

    Age   Salary  Experience
0  25.0  50000.0         1.0
1  30.0      NaN         3.0
2   NaN  60000.0         5.0
3  45.0  65000.0         NaN
4  50.0      NaN        10.0

In [137]:
#User- Defined Functions for missing values handling
#exercise 1: Remove Rows with Missing Values

def remove_missing_rows(dataframe):
  return dataframe.dropna()

In [138]:
#Usage:
df_no_missing= remove_missing_rows(df)
df_no_missing

    Age   Salary  Experience
0  25.0  50000.0         1.0

In [139]:
#Exercise 2: Mean Imptation
def mean_imputation(dataframe,column_name):
  mean_value = dataframe[column_name].mean()
  dataframe[column_name] = dataframe[column_name].fillna(mean_value)
  return dataframe

In [140]:
#Usage:
df_mean = mean_imputation(df.copy(),'Age')
df_mean

    Age   Salary  Experience
0  25.0  50000.0         1.0
1  30.0      NaN         3.0
2  37.5  60000.0         5.0
3  45.0  65000.0         NaN
4  50.0      NaN        10.0

In [141]:
#Exercise 3 : Meadian Imputation
def median_imputation(dataframe ,column_name):
  median_value = dataframe[column_name].median()
  dataframe[column_name] = dataframe[column_name].fillna(median_value)
  return dataframe

In [142]:
#Usage:
df_median = median_imputation(df.copy(),'Salary')
df_median

    Age   Salary  Experience
0  25.0  50000.0         1.0
1  30.0  60000.0         3.0
2   NaN  60000.0         5.0
3  45.0  65000.0         NaN
4  50.0  60000.0        10.0

In [143]:
#Exercise 4 : Mode Imputation
def mode_imputation(dataframe ,column_name):
  mode_value = dataframe[column_name].mode()[0]
  dataframe[column_name] = dataframe[column_name].fillna(mode_value)
  return dataframe

In [144]:
#Usage:
df_mode = mode_imputation(df.copy(),'Experience')
df_mode

    Age   Salary  Experience
0  25.0  50000.0         1.0
1  30.0      NaN         3.0
2   NaN  60000.0         5.0
3  45.0  65000.0         1.0
4  50.0      NaN        10.0

In [145]:
#Exercise 5 : Forward Fill (ffill)
def forward_fill(dataframe ,column_name):
  dataframe[column_name] = dataframe[column_name].fillna(method = 'ffill')
  return dataframe

In [146]:
#usage
df_ffill = forward_fill(df.copy(),'Salary')
df_ffill

/tmp/ipykernel_786/594927243.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dataframe[column_name] = dataframe[column_name].fillna(method = 'ffill')

    Age   Salary  Experience
0  25.0  50000.0         1.0
1  30.0  50000.0         3.0
2   NaN  60000.0         5.0
3  45.0  65000.0         NaN
4  50.0  65000.0        10.0

In [147]:
#Exercise 6:Backward Fill (bfill)
def backward_fill(dataframe ,column_name):
  dataframe[column_name] = dataframe[column_name].fillna(method = 'bfill')
  return dataframe

In [148]:
#usage
df_bfill = backward_fill(df.copy(),'Experience')
df_bfill

/tmp/ipykernel_786/190719058.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dataframe[column_name] = dataframe[column_name].fillna(method = 'bfill')

    Age   Salary  Experience
0  25.0  50000.0         1.0
1  30.0      NaN         3.0
2   NaN  60000.0         5.0
3  45.0  65000.0        10.0
4  50.0      NaN        10.0